### ISSUE TITLE
Code missing from repository?

### ISSUE THREAD

**Issue by ericleib** [cmusphinx/pocketsphinx-android#13]
I am looking for the complete `edu.cmu.pocketsphinx` java package (in particular `edu.cmu.pocketsphinx.Decoder`). As mentioned in the readme, the code is separated between three repositories (*pocketsphinx-android*, *pocketsphinx* and *sphinxbase*).

This repository only contains classes specific to Android.
The [pocketsphinx repository](https://github.com/cmusphinx/pocketsphinx) and [sphinxbase repository](https://github.com/cmusphinx/sphinxbase) are practically only C code.

Or am I missing something obvious?

**Comment by nshmyrev** [comment]
Yes, you need to learn how SWIG works.
