### ISSUE TITLE
Importing file grammars from a jsgf string grammar

### ISSUE THREAD

**Issue by curobosqui** [cmusphinx/pocketsphinx-android#16]
I'm using pocketsphinx-android with the asset sync utility. I am able to use grammars that I add as a string using Decoder.setJsgfString , and also able to import rules from one .gram file to another one with "import &lt;grammar_file.rule_name&gt;.

What I haven't been able to do so far is to use import statements in a string grammar to import asset/file grammars. I have tried using only the grammar filename, full path and only the package. These are the error messages I get in adb logcat:

Filename only

    com.sample.vr.commands E/cmusphinx: ERROR: "jsgf.c", line 775: Failed to find grammar actions.gram

Package

    com.sample.vr.commands E/cmusphinx: ERROR: "jsgf.c", line 775: Failed to find grammar com/sample/vr/commands/files/sync/actions.gram

Full path

    com.sample.vr.commands E/cmusphinx: ERROR: "jsgf.c", line 775: Failed to find grammar /storage/emulated/0/Android/data/com/sample/vr/commands/files/sync/actions.gram

Is there a way to tell pocketsphinx-android where to look for grammar files? they are indeed in the files/sync directory, but the .c code seems to replace the dots to slashes in the path (in the function `jsgf_import_rule` of the sphinxbase/src/libsphinxbase/lm/jsgf.c file near line 787).

**Comment by nshmyrev** [comment]
Already asked here

http://stackoverflow.com/questions/35007985/import-grammar-rules-from-string-based-grammar

please avoid posting to multiple places at once
