### ISSUE TITLE
Cannot build with latest sphinxbase

### ISSUE THREAD

**Issue by nachogoro** [cmusphinx/pocketsphinx-android#17]
Commit https://github.com/cmusphinx/sphinxbase/commit/12710904db83788f438dd14ab4e4c13acc33d63c in sphinxbase has broken the ability to build pocketsphinx-android:
> make: *** No rule to make target `../sphinxbase/src/libsphinxbase/util/huff_code.c', needed by `obj/local/arm64-v8a/objs/sphinxutil/huff_code.o'.  Stop.

**Comment by nshmyrev** [comment]
Fixed, thank you for the report!
