### ISSUE TITLE
RecognitionListener callbacks cause UI hang ups

### ISSUE THREAD

**Issue by jameel263** [cmusphinx/pocketsphinx-android#18]
Are there any specific reasons that SpeechRecognizer's RecognitionListener callbacks are called on the main thread? I find that this often reduces the app responsiveness.

**Comment by nshmyrev** [comment]
Well, you might know how to adjust UI from other thread but many unexperienced users lack this knowledge. It is like every UI handler, don't do too expensive things there.

There is an issue that onResult (final result computation) takes long time and it is performed in UI thread. This is a real issue indeed tracked here: 

https://sourceforge.net/p/cmusphinx/bugs/423

**Comment by jameel263** [comment]
Well that's a tad obvious. The reason I asked this question was to understand the reasoning behind the usage of the main thread in the first place. If there is no specific reason behind calling everything on the main thread, I was going to create a feature to allow the user to simply pass in the handler he wants the callbacks called on. That way you don't need to manage the threading for every callback if you wanted it on a non ui thread.

Thanks for the clarification on the onResult. I came across the source forge link but didn't realise they were talking about the final result computation.

**Comment by nshmyrev** [comment]
Ok, please let me know if you need any help. I wanted to redesign API a little bit to automatically raise `onResult` thus we'll solve thread issue. I am not sure on timeline though.
