### ISSUE TITLE
ABI Filter for x86 in Gradle script

### ISSUE THREAD

**Issue by mahula** [cmusphinx/pocketsphinx-android#22]
Can the ABI filter for x86 be added to build.gradle, please?
The resulting aar will then also contain the JNI library for this architecture. It is quite helpful for testing Android app build around the library, e.g. pocketsphinx-android-demo in an emulator using x86 images and also for x86 devices running Android, on which such apps can be run.

**Comment by nshmyrev** [comment]
Done, thanks

**Comment by mahula** [comment]
Thank you.

**Comment by DefCon-007** [comment]
I am developing for MIPS architecture can you please help @nshmyrev
