### ISSUE TITLE
PocketSphinx-Android :Silence detection is too quick, not allowing for natural speech pauses.

### ISSUE THREAD

**Issue by BeanStalka** [cmusphinx/pocketsphinx-android#26]
Is there any way to set the amount of time after silence is detected and when the utterance is considered completed?

My testing indicates that if .8 seconds of silence is detected, the ICMURecognizer.OnEndOfSpeech event is raised.

Hopefully, I can change this to 1.25 secs or 1.5 secs in order to allow for a more natural pause between the wake word and the remainder of the utterance.

As always, any help or suggestion would be greatly appreciated.

**Comment by nshmyrev** [comment]
Try

       config.setInt('-vad_postspeech', 125)

**Comment by BeanStalka** [comment]
That seems to be working nicely.

I'm sure that's in the documentation somewhere.  Do you have a link to all of those parameters available?

Thank way I can find it for myself.

Thanks a bunch
