### ISSUE TITLE
Pocketsphinx -  many false positives for wake phrase after training

### ISSUE THREAD

**Issue by BeanStalka** [cmusphinx/pocketsphinx-android#28]
I am using pocketsphinx to detect a wakeword and have slimmed down the required files as much as possible.

I have a wakephrases.txt with one  phrase and a dictionary with the two words that make up the phrase.

I created a one hour recording of several of my favorite rock bands, then inserted the wake phrase in 30 spots.  I dialed in the threshold for the wake phrase, using the pocket_sphinx_continuous

"pocketsphinx_continuous.exe -infile sync\test\test.wav -hmm sync\en-us-ptm -dict sync\en-us-wakeword.dict -kws sync\en-us-wakephrases.txt -time yes -logfn output.log"

Unfortunately it is is still getting a ton of false positives, basically any speech in a quiet room will trigger it. Like say during a sprint review. :(

Question time:
1.) Is there anything else I can do to help dial in my key phrase?  A setting I can tweak?  I saw somewhere that I might need to include the SIL in my dictionary.  Is this true?

2.) Are any walkthroughs or maybe you could tell me what the proper threshhold is for this phrase and how you arrived at it?

Please see the attached files and as always, thank you for whatever help you can give,

[en-us-wakephrases.txt](https://github.com/cmusphinx/pocketsphinx-android/files/1065223/en-us-wakephrases.txt)

[en-us-wakeword.dict.txt](https://github.com/cmusphinx/pocketsphinx-android/files/1065224/en-us-wakeword.dict.txt)

[RecognizerSetup.txt](https://github.com/cmusphinx/pocketsphinx-android/files/1065229/RecognizerSetup.txt)

**Comment by BeanStalka** [comment]
I haven't heard back from anyone in a while.  

I have been reading your documentation and it seems like i may be able to use a .gram implementation.  Would you suggest this for picking up a command like wake word.

I have to start final threshold testing today, and I do not think we will be able to get to the needed accuracy using the keyword spotting at any threshold

Please let me know if you think that using a .gram file is a valid approach.

We may have to abandon pocketsphinx entirely if we cannot get the detection under control.

Please help

**Comment by nshmyrev** [comment]
To get help on accuracy you need to provide an audio data to reproduce your problem, covered at:

https://cmusphinx.github.io/wiki/faq/#q-why-my-accuracy-is-poor

**Comment by BeanStalka** [comment]
I'm currently key word spotting.  I read that re training the model is not
needed.

Is that true?

Also I have been using sphinx_continious with a one hour file to dual in
the threshold.

Should I be using key word spotting or the grammar approach?

I only need to wake on one phrase.  But I need to get it consistently.

**Comment by nshmyrev** [comment]
You can share your audio file to get help on this.

**Comment by BeanStalka** [comment]
Attached please find a zip containing the .wav file with my wake phrase.

[OKWellBe.zip](https://github.com/cmusphinx/pocketsphinx-android/files/1078543/OKWellBe.zip)

**Comment by nshmyrev** [comment]
There are several issues with your file

1) File is 44khz, pocketsphinx expects 16khz

2) You have breaks in the audio means your system is not running smooth, maybe the CPU is too weak.

3) You have distant recording, you need much better microphone for that then (microphone array) and you need to eliminate echo. In case you still going to have echo you have to train (not adapt but train) a special acoustic model to recognize audio with echo.

Until you solve those problems it is not easy to expect a good spotting accuracy.

**Comment by BeanStalka** [comment]
So about that file.

I recorded on my device after a successful wake word detection.

I then used audacity to amplify it in order to use it in my sample file
used with pocketsphinx_continious.

I am formatting the raw data as a .wav but was having trouble opening it up
on my desktop.

I will do a  direct dump out of the buffer and post that file (.raw).  That
one should be in better shape

I know I have an issue with the gain in my recordings.  I'm using a
Bluetooth speaker's mic to record it.

I will prob need a new mic.  Or mic array.  Do you know any that will work
with a Samsung Galaxy tab S2?

**Comment by nshmyrev** [comment]
> I will prob need a new mic.  Or mic array.  Do you know any that will work
with a Samsung Galaxy tab S2?

I don't think Android is a good platform for such development, you can get something like this instead:
https://github.com/alexa/alexa-avs-sample-app/wiki/Conexant2Mic-Raspberry-Pi

**Comment by BeanStalka** [comment]
Unfortunately That is not an option at this point.

I am familiar with AGC, and was wondering if you could briefly explain the
pocketsphinx implementation of such.

none,max, emax, noise

Which one of the above only apply AGC to the voice portion and not the
silence or noise.

**Comment by BeanStalka** [comment]
Nickolay I haven't heard back in a while and had another question.

I read that if I could set the AudioSource.VoiceCommunication enum when newing up a AudioRecord object I can help with cleaning up the audio data.

Is there anyway to configure pocketsphinx to use AudioSource.VoiceCommunication if it is not already?

P.S. - I found a couple of microphones that pug into the audio jack that I have purchased and can't wait to use.

**Comment by nshmyrev** [comment]
@BeanStalka you have to recompile the sources but it is more or less straightforward to change the source, see this line:
```
        recorder = new AudioRecord(
                AudioSource.VOICE_RECOGNITION, sampleRate,
                AudioFormat.CHANNEL_IN_MONO,
                AudioFormat.ENCODING_PCM_16BIT, bufferSize * 2);
```
in SpeechRecognizer constructor.

**Comment by nshmyrev** [comment]
Also take a note that your issue is not noise, but reverberation. Most noise cleanup algorithm reduce speech recognition accuracy because they corrupt speech. Thats why VOICE_RECOGNITION probably applies less noise cancellation than VOICE_COMMUNICATION.

**Comment by BeanStalka** [comment]
I'm hunting down a good USB mic to help remove that reverb.

What AudioSource does the current pocket sphinx use?

**Comment by nshmyrev** [comment]
VOICE_RECOGNITION as listed above

**Comment by BeanStalka** [comment]
OK, it seems like there is no issue with that setting.

Ill get the USB mic and try with that.  

As always, thank your for your time any help.

**Comment by BeanStalka** [comment]
Maybe this is another thread/issue.

I set this in my code:
_pocketSphinxRecognizer.Decoder.SetRawdataSize(300000)

from our previous conversations you mentioned this is a circular buffer.

How do I find the index of the most recently written data.

I am key word spotting and plan on this approach

1.) ICMURecognizer.OnPartialResult - start a timer 
2.) ICMURecognizer.OnEndOfSpeech() - stop timer and calculate the size of my data based on ByteRate
3.) Find the most recent entry in the circular buffer and and work backwards.  Taking the data in the raw data buffer added between OnPartialResult and OnEndOfSpeech

All I need to be able to take advantage of this buffer is the last write location on the buffer

As always I appreciate your help.
