### ISSUE TITLE
Build language model in Android device (Java)

### ISSUE THREAD

**Issue by icaksama** [cmusphinx/pocketsphinx-android#36]
Hi all, I need some help with pocketsphinx for Android.
I want to create offline speech recognition with language model with dynamic vocabulary. Is that possible to build language model with Java? 
So, I can use Array String as the vocabulary for that language model.

**Comment by icaksama** [comment]
I have found the answer and make it to the android library. Please check here https://github.com/icaksama/RapidSphinx

**Comment by nshmyrev** [comment]
Congratulations!
