### ISSUE TITLE
pocketsphinx, maven, dl.bintray.com not found

### ISSUE THREAD

**Issue by thomasflynn** [cmusphinx/pocketsphinx-android#42]
Hi there.  In the README.md on your repo, it suggests to add "https://dl.bintray.com" to the list of repositories and add "implementation 'edu.cmu.pocketsphinx.android:pocketsphinx-android:5prealpha@aar' to the dependencies in the gradle file.

I'm not seeing dl.bintray.com as existing.  I get a 404.  has the maven repo moved somewhere else?  Thanks.

**Comment by nshmyrev** [comment]
it is wip, not yet working.

**Comment by Anth06ny** [comment]
same
