### ISSUE TITLE
Is there any way i get back audio file? 

### ISSUE THREAD

**Issue by ameerhamza6733** [cmusphinx/pocketsphinx-android#44]
is there any way I get back the audio file with the final result?

**Comment by nshmyrev** [comment]
Yes, you can check getRawData example 

https://github.com/cmusphinx/pocketsphinx/blob/master/swig/java/test/DecoderTest.java#L45

**Comment by ameerhamza6733** [comment]
Sir, i have tried  but this rawData array size is zero witches mean null , what i am doing wrong?

        @Override
        public void onResult(Hypothesis hypothesis) {

            String words = hypothesis.getHypstr();
            Log.d(TAG, "hypothiesis: " + words);

            short[] rawdata = mPocketSphinxRecognizer.getDecoder().getRawdata();
            if (rawdata.length > 1) {

            } else {
                Log.e(TAG, "rawdata : " + rawdata);
            }
        }

**Comment by ameerhamza6733** [comment]
Thank you, sir, I finally able to save .raw in my storage this how I did it 

 private void setupRecognizer(File assetsDir) throws IOException {
        // The recognizer can be configured to perform multiple searches
        // of different kind and switch between them

        recognizer = SpeechRecognizerSetup.defaultSetup()
                .setAcousticModel(new File(assetsDir, "en-us-ptm"))
                .setDictionary(new File(assetsDir, "cmudict-en-us.dict"))
                .getRecognizer();

        recognizer.addListener(mRecognitionListener);
        recognizer.getDecoder().setRawdataSize(300000);

        recognizer.addKeyphraseSearch(KWS_SEARCH, KEYPHRASE);


    }


 @Override
        public void onResult(Hypothesis hypothesis) {
            Log.d(TAG, "onResult: " +  + recognizer.getDecoder().getRawdata().length);

            if (hypothesis != null) {
                String text = hypothesis.getHypstr();
            }
          Decoder decoder= recognizer.getDecoder();
            short[] data = decoder.getRawdata();
            try {
                DataOutputStream dos = new DataOutputStream(new FileOutputStream(Utils.getPublicStorageDir("recoding",".raw")));
                for (int i = 0; i < data.length; i++) {
                    dos.writeShort(data[i]);
                }
                dos.close();
            } catch (Exception e) {
                e.printStackTrace();
            }

        }


I have tried converting this .raw file into audio but i can't able to convert, so the question am i doing right? if yes then how do i compress this raw into the valid audio file?

**Comment by nshmyrev** [comment]
> so the question am i doing right?

No

**Comment by ameerhamza6733** [comment]
Sir can you please tell me, how i do it right?
