### ISSUE TITLE
continuous audio after keyword detection

### ISSUE THREAD

**Issue by zachadasm16** [cmusphinx/pocketsphinx-android#50]
Is there anyway I could say something like "Ok google take a picture" and I would detect the wakeword using keyword search and get that next stream of audio which is the command

**Comment by nshmyrev** [comment]
You can access the audio recorded once keyword is detected with getRawData and feed it to recognizer again. Large vocabulary command recognition on the phone is not possible anyway, you have to send the data to the cloud.

**Comment by zachadasm16** [comment]
I am using a very small library for speech recognition so I do not believe the cloud is necessary since it is only a few commands

**Comment by nshmyrev** [comment]
Ok, then you can get raw data and feed it to the decoder again to recognize with the grammar.

**Comment by zachadasm16** [comment]
Ok thank you

**Comment by zachadasm16** [comment]
Sorry, one more question, would I have to stop or cancel the recognizer before I call get raw data or call that and then cancel or stop it?

**Comment by nshmyrev** [comment]
In endOfSpeech (when silence occured) if partial result contained keyword you cancel the recognizer, then get raw data, then send it for another decoding. When keyword is detected you don't cancel yet, you want to wait till the silence.

**Comment by zachadasm16** [comment]
Ok understood. Thanks for the help!

**Comment by zachadasm16** [comment]
when i call the decoder on the raw data it is calling phone_loop_search.c when i specified setsearch to ngram search. is there another way I have to specify the type of search when I call the decoder

**Comment by nshmyrev** [comment]
phone_loop search is secondary search, it is enabled with ngram for speed. Search is selected by name with setSearch call.
