### ISSUE TITLE
decoding raw audio files

### ISSUE THREAD

**Issue by zachadasm16** [cmusphinx/pocketsphinx-android#52]
what is the proper way to decode raw audio files using an ngram search?

**Comment by nshmyrev** [comment]
It is not different from any other decoding. Like here https://github.com/cmusphinx/pocketsphinx/blob/master/swig/java/test/DecoderTest.java. Not sure what your problem is.

**Comment by zachadasm16** [comment]
I got this after I left the comment and forgot to close. Thank you

**Comment by zachadasm16** [comment]
Also Ive done it this way but is there anyway to getRawdata then pass it to a decoder without saving it to a file?

**Comment by zachadasm16** [comment]
because I am calling getRawData(0 which puts the data in a short[]. Is there anyway I can directly pass that data to a decoder or do I have to save it as a raw file then pass the raw file to a decoder?
