### ISSUE TITLE
Issue when changing used model

### ISSUE THREAD

**Issue by TheZeldaBoss** [cmusphinx/pocketsphinx-android#54]
Hello,

I'd like to use pocketsphinx to recognize french language phonemes, on an android application.
I have downloaded the demo application for android, and I tried to modify the accoustic model and dictionary, but all I get now is an error :
E/cmusphinx: ERROR: "fsg_search.c", line 141: The word 'phones' is missing in the dictionary
I had some other errors like that that I have been able to remove by replacing the original english words by french ones, but even if I changed everything, this error is still there.
I'm using the french model from here : https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/

Any solutions ?

**Comment by nshmyrev** [comment]
Seems like this word is still in the grammar, you need to search better ;)

**Comment by nshmyrev** [comment]
You can upload your whole modified package, I'll take a look.

**Comment by TheZeldaBoss** [comment]
nevermind, found it, it was just that some of the files (the .gram, the ones with the specific words to use in menus) were still not changed... It works well now. Sorry for the disturbance.
